security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
    access_control:
         - { path: ^/api, roles: ROLE_USER }
         - { path: ^/profile, roles: ROLE_USER }
