version: "3.7"
services:
  app:
    image: sk/app
    build:
      context: ./docker/app
  nginx:
    image: sk/nginx
    build:
      context: ./docker/nginx
  pg:
    image: postgres:13
    volumes:
      - /opt/pg/sk_data:/var/lib/postgresql/data
